// Marvish Chandra

#include <iostream>

class ExpediaInfo{
    public:
    string sortIndex;
    string hotelId;
    string name;
    string localizedName;
    string nonLocalizedName;
    string address;
    string city;
    string stateProvinceCode;
    string countryCode;
    string postalCode;
    string airportCode;
    string supplierType;
    string hotelStarRating;
    string hotelStarRatingCssClassName;
    string hotelGuestRating;
    string totalRecommendations;
    string percentRecommended;
    string totalReviews;
    string shortDescription;
    string locationDescription;
    string locationId;
    string lowRate;
    // string lowRateInfo;
    string rateCurrencyCode;
    string rateCurrencySymbol;
    string roomsLeftAtThisRate;
    string latitude;
    string longitude;
    string proximityDistanceInMiles;
    string proximityDistanceInKiloMeters;
    string largeThumbnailUrl;
    string thumbnailUrl;
    string discountMessage;
    string isDiscountRestrictedToCurrentSourceType;
    string isSameDayDRR;
    boolean isHotelAvailable;
    string notAvailableMessage;
    string isSponsoredListing;
    string clickTrackingUrl;
    string clickTrackingRedirectUrl;
    string impressionTrackingUrl;
    string omnitureAdDisplayedUrl;
    string omnitureAdClickedUrl;
    string hasFreeCancellation;
    string amenities;
    string distanceUnit;
    string didGetBackHighestPriceFromSurvey;
    string highestPriceFromSurvey;
    string isDudley;
    string isVipAccess;
    string isPaymentChoiceAvailable;
    string isShowEtpChoice;
    string allowedToDisplayRatingAsStars;
    string jsonHotelBrand;
    string isMemberDeal;
    string isMobileExclusive;
    string fallbackImage;

    public static void expediaDesc(String [] args){
        ExpediaInfo expediaDetails;
        expediaDetails.sortIndex = "Sort index used to restore original sort order";
        expediaDetails.hotelId = "Hotel Id (primary hotel identifier, used for subsequent calls to details or booking).";
        expediaDetails.name = "Plain formatted name of hotel.";
        expediaDetails.localizedName = "Plain localized formatted name of hotel.";
        expediaDetails.nonLocalizedName = "Plain formatted name of hotel.";
        expediaDetails.address = "Address of hotel.";
        expediaDetails.city = "City where the hotel is located.";
        expediaDetails.stateProvinceCode = "2 character state/province code where the hotel is locate.";
        expediaDetails.countryCode = "2 character country code where the hotel is located.";
        expediaDetails.postalCode = "Postal/zip code of the hotel.";
        expediaDetails.airportCode = "Airport code associated with the hotel.";
        expediaDetails.supplierType = "Supplier type of the hotel listing.";
        expediaDetails.hotelStarRating = "Star Rating of the hotel.";
        expediaDetails.hotelStarRatingCssClassName = "Star Rating of the hotel expressed in a format compatible with CSS (the decimal point is replaced by a '-')";
        expediaDetails.hotelGuestRating = "The overall guest rating for this hotel.";
        expediaDetails.totalRecommendations = "The total number of recommendations made by expedia users.";
        expediaDetails.percentRecommended = "The percentage of users who recommended this hotel.";
        expediaDetails.totalReviews = "The total number reviews made by expedia users. Returns -1 if review data is not available for the hotel.";
        expediaDetails.shortDescription = "Short Description of the hotel.";
        expediaDetails.locationDescription = "Neighborhood or general location information of the property if available.";
        expediaDetails.locationId = "Region id of the location/neighborhood.";
        expediaDetails.lowRate = "Formatted string representing lowest rate for the stay.";
        expediaDetails.lowRateInfo = "Detail information about the lowest rate offer.";
        expediaDetails.rateCurrencyCode = "Currency code with respect to the lowRate.";
        expediaDetails.rateCurrencySymbol = "Currency symbol with respect to the lowRate.";
        expediaDetails.roomsLeftAtThisRate = "The number of rooms left at the lowRate.";
        expediaDetails.latitude = "Latitude of the hotel location.";
        expediaDetails.longitude = "Longitude of the hotel location.";
        expediaDetails.proximityDistanceInMiles = "The distance in miles the hotel location from the city center.";
        expediaDetails.proximityDistanceInKiloMeters = "The distance in kilometers the hotel location from the city center.";
        expediaDetails.largeThumbnailUrl = "URL Fragment identifying a larger 180x180 thumbnail image; base host is images.trvl-media.com.";
        expediaDetails.thumbnailUrl = "URL Fragment identifying a 90x90 thumbnail image; base host is images.trvl-media.com.";
        expediaDetails.discountMessage = "Discount message associated with the hotel. This field is not available if no discount is available.";
        expediaDetails.isDiscountRestrictedToCurrentSourceType = "Whether this promo is restricted to the given source type";
        expediaDetails.isSameDayDRR = "Whether this promo is restricted to the current day";
        expediaDetails.isHotelAvailable = true;
        expediaDetails.notAvailableMessage = "A hard coded message indicating that the hotel is not available. This field is not returned if the hotel is available.";
        expediaDetails.isSponsoredListing = "Describes whether a hotel is sponsored from Hook Logic.";
        expediaDetails.clickTrackingUrl = "Url for tracking when user clicks an ad.";
        expediaDetails.clickTrackingRedirectUrl = "Url for tracking when user clicks an ad. Url results in a redirect.";
        expediaDetails.impressionTrackingUrl = "Url for registering when an ad is shown to a user.";
        expediaDetails.omnitureAdDisplayedUrl = "Omniture tagging: Url for displaying an ad.";
        expediaDetails.omnitureAdClickedUrl = "Omniture tagging: Url for clicking an ad.";
        expediaDetails.hasFreeCancellation = "Whether the hotel offers free cancellation.";
        expediaDetails.amenities = "List of room amenities for the lowest rate offer.";
        expediaDetails.distanceUnit = "Miles or Kilometers";
        expediaDetails.didGetBackHighestPriceFromSurvey = "Check whether highest price surveys are available for current hotel. DEPRECATED.";
        expediaDetails.highestPriceFromSurvey = "Highest survey price to show as strikethrough if applicable. DEPRECATED.";
        expediaDetails.isDudley = "Flag to indicate whether it is a Dudley Hotel";
        expediaDetails.isVipAccess = "Flag to indicate whether this hotel honors Expedia VIPs.";
        expediaDetails.isPaymentChoiceAvailable = "Are ETP offers available?";
        expediaDetails.isShowEtpChoice = "Is Pay Later option available?";
        expediaDetails.allowedToDisplayRatingAsStars = "Flag to indicate to whether or not to display the star rating with a star icon or an alternate";
        expediaDetails.jsonHotelBrand = "Brand information if applicable";
        expediaDetails.isMemberDeal = "Whether the offer available is a member deal or not";
        expediaDetails.isMobileExclusive = "Whether the offer available is a mobile exclusive deal or not";
        expediaDetails.fallbackImage = "Fallback image for Travel Ads";
    };
};